In [2]:
# Basics about numpy

In [3]:
# import the module 
import numpy as np 

In [4]:
# convert a list to an array
my_list = [1,2,3,4,5]

# we can pass a list and specify the type of an array in which we want to change 
arr = np.array(my_list,np.int32)
arr

array([1, 2, 3, 4, 5])

In [5]:
# data type of an array
arr.dtype

dtype('int32')

In [6]:
#size of an array
arr.shape # 1-d array with 5 elements 

(5,)

In [7]:
new_arr = np.array([[1,2,3],[4,5,6]])
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# dimension of an array
new_arr.shape

(2, 3)

In [9]:
# change the shape of an array 
new_arr.reshape(3,2) # we have to mantain the shape of an orignal array 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# Change shape
new_arr.reshape(1,6) # Product is 1x6 = 6

array([[1, 2, 3, 4, 5, 6]])

In [11]:
# Convert a tuple to array
arr_from_tup = np.array((3.4,4.5,5.3,6.6))
arr_from_tup

array([3.4, 4.5, 5.3, 6.6])

In [12]:
# Shape of array
arr_from_tup.shape


(4,)

In [13]:
# data Type of array
arr_from_tup.dtype


dtype('float64')

In [14]:
# Create an array from 1 to 10
np.arange(start=1, stop=10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Create an array from 1 to 10 with step-size=2
np.arange(start=1, stop=10, step=2)


array([1, 3, 5, 7, 9])

In [16]:
# Right now its 1D
np.arange(1,10,2).shape

(5,)

In [17]:
# Convert to 2D
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [18]:
np.arange(50,1,-1)


array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [19]:
np.arange(1,18,3)
np.arange(1,18,3).shape
np.arange(1,18,3).reshape(2,3)


array([[ 1,  4,  7],
       [10, 13, 16]])

In [20]:
# linspace -- equally spaced elements
np.linspace(1,20,30) # 30 number of elements between 1 to 20 


array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [21]:
# reshaping
np.linspace(1,20,30).reshape(3,10)


array([[ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
         4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172],
       [ 7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
        10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586],
       [14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
        17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ]])

In [22]:
# zeros
np.zeros(3)


array([0., 0., 0.])

In [23]:
# zeros
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# ones
np.ones(3)


array([1., 1., 1.])

In [25]:
# ones
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
# ones
np.ones((5,2,8))
# 2,8 denotes the inner most array of 2 rows and 8 columns
# and there are 5 sets of 2,8 arrays making it 3D array

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [27]:
#We can create an array whose initial content is random and depends on the state of the memory.
#The reason to use empty over zeros is speed - just make sure to fill every element afterwards!
# empty
np.empty((3,7))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.67293691e-307, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306],
       [6.23057349e-307, 1.02360935e-306, 1.69120416e-306,
        1.78022342e-306, 6.23058028e-307, 1.06811422e-306,
        1.39071445e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        2.56765117e-312]])

In [28]:
# identity matrix of 4x4 shape
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
arr = np.array([4,3,6,7,1,9])
print(arr)
np.sort(arr)

[4 3 6 7 1 9]


array([1, 3, 4, 6, 7, 9])

In [30]:
 # Concatenating same size of two array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
# Concatenating different sizes of array by axis=0
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
# Concatenating different sizes of array by axis=1
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [33]:
arr = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],
[[0, 1, 2, 3], [4, 5, 6, 7]],
[[0 ,1 ,2, 3], [4, 5, 6, 7]]])
arr.ndim # gives the dimension of the array

3

In [34]:
arr.size


24

In [35]:
arr.shape

(3, 2, 4)

In [36]:
# arr.reshape()
arr = np.arange(12) # here size is 12

In [37]:
print(arr)
print()
# reshaping into 2D array of Rows=2 and Columns=6, Size = 12
print(arr.reshape(2,6))
print()
# reshaping into 2D array of Rows=4 and Columns=3, Size = 12
print(arr.reshape(4,3))
print()
# reshaping into 3D array of 3,2,2 maintaining the Size = 12
print(arr.reshape(3,2,2))
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]



In [38]:
#Random number generation (Uniform distribution)
np.random.rand(2,3)


array([[0.68000164, 0.51453395, 0.36276301],
       [0.49783102, 0.01232436, 0.34173955]])

In [39]:
#Random number generation (Normal distribution with Mean=0 & Standard Deviation=1)
np.random.randn(2,3)


array([[-0.94861669, -1.12874115,  1.00171302],
       [-0.87723608, -1.48122459, -0.16653681]])

In [40]:
np.random.randint(low=1, high=100, size=10) # here size=10, which gives 10 number between min and max limit


array([93, 47, 41, 88, 64, 64,  5, 35, 96, 12])

In [41]:
# we can create a n-dimensional array by specifying the size
np.random.randint(1,100,(4,4)) # here it is 4x4 size of array having random values

array([[20, 99, 99, 43],
       [58, 63, 18, 69],
       [27, 14, 13,  5],
       [79, 69, 42, 60]])

In [42]:
#Return random floats in the half-open interval [0.0, 1.0).
np.random.random_sample(size=(2,6))

array([[0.10889774, 0.55975458, 0.93516403, 0.24536082, 0.8727355 ,
        0.50593125],
       [0.00828479, 0.6833436 , 0.83475357, 0.20006734, 0.87910646,
        0.01755845]])

In [43]:
#Draw random samples from a normal (Gaussian) distribution
np.random.normal(loc=0, scale=1, size=15) # 'loc' denotes mean & 'scale'denotes Standard Deviation for 15 numbers

array([-0.09235699,  0.59543217, -0.87103198,  2.09146802, -0.12324493,
       -0.51844483,  0.61321809,  1.2443144 ,  1.94915518, -2.50475843,
        0.46781709,  0.7894154 ,  0.8080644 , -1.32959068, -0.55143701])

In [44]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# data at position 1
arr[1]

1

In [46]:
# data from position 2 till the end of array
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# data between position 2 and 7 (exclusive)
arr[2:7]

array([2, 3, 4, 5, 6])

In [48]:
# Negative indexing from last till 3rd last
arr[-1:7:-1]

array([10,  9,  8])

In [49]:
# Negative indexing from last till 3rd last
arr[-1:-4:-1]

array([10,  9,  8])

In [50]:
# print all of the values in the array that are less than equal to 5
arr[arr<=5]

array([0, 1, 2, 3, 4, 5])

In [51]:
# select elements that satisfy two conditions using the & and | operators
arr[(arr<=8) & (arr>2)]

array([3, 4, 5, 6, 7, 8])

In [52]:
arr1 = np.random.randint(2,100,20).reshape(5,4)
arr1

array([[62, 33, 94, 12],
       [78, 99, 37, 66],
       [39, 89, 41, 38],
       [ 7, 16, 16, 34],
       [23, 36, 53, 67]])

In [53]:
# all data till 3rd row and all data till 3rd column
arr1[:3,:3]

array([[62, 33, 94],
       [78, 99, 37],
       [39, 89, 41]])

In [54]:
# all data starting from 3rd row and all data starting from 1st column
arr1[3:,1:]

array([[16, 16, 34],
       [36, 53, 67]])

In [55]:
# all data starting from 2nd row till 3rd row and all data of 1st and last column
arr1[2:4,[0,-1]]

array([[39, 38],
       [ 7, 34]])

In [56]:
5 + np.ones((3,5)) # add 5 to all elements in an array

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [57]:
arr1 = np.random.randint(1,20,(2,2))
arr2 = np.random.randint(10,20,(2,2))

In [59]:
print(f"Array1: \n{arr1}")
print(f"\nArray2: \n{arr2}")

Array1: 
[[16 16]
 [13  2]]

Array2: 
[[13 14]
 [18 17]]


In [60]:
print(f"\n Addition: \n{arr1 + arr2}")
print(f"\n Subtraction: \n{arr1 - arr2}")
print(f"\n Multiplication: \n{arr1 * arr2}")
print(f"\n Division: \n{arr1 / arr2}")


 Addition: 
[[29 30]
 [31 19]]

 Subtraction: 
[[  3   2]
 [ -5 -15]]

 Multiplication: 
[[208 224]
 [234  34]]

 Division: 
[[1.23076923 1.14285714]
 [0.72222222 0.11764706]]


In [61]:
# sum
print(arr1)
print("Sum without axis", arr1.sum())
print("Sum axis=0", arr1.sum(axis=0))
print("Sum axis=1", arr1.sum(axis=1))

[[16 16]
 [13  2]]
Sum without axis 47
Sum axis=0 [29 18]
Sum axis=1 [32 15]


In [62]:
# Addition
arr1 + arr2

array([[29, 30],
       [31, 19]])

In [64]:
np.sqrt(arr1)

array([[4.        , 4.        ],
       [3.60555128, 1.41421356]])

In [65]:
np.exp(arr2)

array([[  442413.39200892,  1202604.28416478],
       [65659969.13733051, 24154952.7535753 ]])

In [66]:
np.log10(arr1)

array([[1.20411998, 1.20411998],
       [1.11394335, 0.30103   ]])

In [67]:
# Broadcasting
arr = np.arange(1,10)
arr[2:] = 1000
print(arr)

[   1    2 1000 1000 1000 1000 1000 1000 1000]


In [68]:
# Broadcasting | NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting.
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [70]:
# Arrays are Reference typed, that means assigning one array to another also shares the same memory reference.add()
# To prevent, the above, we must use copy() method
arr1 = arr.copy()
print(arr)
arr1[3:] = 500
print(arr1)

[   1    2 1000 1000 1000 1000 1000 1000 1000]
[   1    2 1000  500  500  500  500  500  500]


In [71]:
arr1 = np.array([[1,1], [2,2]])
arr2 = np.array([[3,3], [4,4]])
print(f"Vertical Stack: \n{np.vstack((arr1, arr2))}")
print(f"\nHorizontal Stack: \n{np.hstack((arr1, arr2))}")

Vertical Stack: 
[[1 1]
 [2 2]
 [3 3]
 [4 4]]

Horizontal Stack: 
[[1 1 3 3]
 [2 2 4 4]]


In [72]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
arr

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [73]:
unique_values = np.unique(arr) # alternatively, we can remove duplicates from the array
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
unique_values, index_positions = np.unique(arr, return_index=True)
print(unique_values)
print(index_positions)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]


In [75]:
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)
print(counts)

[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


In [76]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
np.arange(start=30, stop=70, step=2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [77]:
# Write a NumPy program to create a 3x3 identity matrix.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
np.random.normal(loc=0, scale=1, size=15) # 'loc' denotes mean & 'scale' denotes Standard Deviation

array([-0.58390569,  0.07437222,  0.92525173, -0.33555916,  2.02992265,
       -1.51328964,  0.55416643, -0.34021709,  0.38612734, -1.46355002,
       -0.35912772,  1.57013723, -0.32312136, -0.56238284,  2.09884485])

In [79]:
# Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
# Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
arr1 = np.array([ 0, 10, 20, 40, 60])
arr2 = np.array([0, 40])
# for i in range(len(arr1)):
# if arr1[i] in arr2:
# arr1[i] = True
# else:
# arr1[i] = False
print("Compare each element of array1 and array2")
np.in1d(arr1, arr2)

Compare each element of array1 and array2


array([ True, False, False,  True, False])

In [81]:
# Write a Python program to find the maximum and minimum value of a given flattened array.
arr = np.array([[0, 1],
[2, 3]])
print(f"Max: {np.amax(arr)}")
print(f"Min: {np.amin(arr)}")

Max: 3
Min: 0
